#front
export WHITE_F="\e[97m"
export RED_F="\e[31m"
export GREEN_F="\e[32m"
export BLUE_F="\e[34m"
export PURPULE_F="\e[35m"
export BLACK_F="\e[30m"
export TERQUOISE_F="\e[36m"
#back
export WHITE_B="\e[107m"
export RED_B="\e[41m"
export GREEN_B="\e[42m"
export BLUE_B="\e[44m"
export PURPULE_B="\e[45m"
export BLACK_B="\e[40m"
export YELLOW_B="\e[43m"
export END="\e[0m"
